### ISSUE TITLE
A problem about the dataset

### ISSUE THREAD

**Issue by hexing2333** [tudelft-cda-lab/SAGE#45]
Hello, is the cptc data set in this experiment under this link? I wonder which of these files should I download? Just like the sample-input.json you gave. Thanks very much!

 **http://mirror.rit.edu/cptc/2018/t5/**

**Comment by hexing2333** [comment]
Hello，I used this data set([suricata_alert.json](http://mirror.rit.edu/cptc/2018/t5/events/suricata_alert.json.gz)) to run your code, and the S-PDFA graph generated is as follows. I would like to know that in the graph generated by Fig.6 in your paper, all circles are IP addresses, but what I generated is similar to "70#1". I would like to know if there is a problem in which step of my experiment?

 
![exp-2018T1 txt](https://github.com/tudelft-cda-lab/SAGE/assets/46010827/eb948b55-8d94-4f96-89b6-d0fd0ea1b0cb)

**Comment by jzelenjak** [comment]
Hello, the CPTC-2018 dataset in the link is correct, however this is only for team 5. In the experiments, we use all teams (which you can find in [the parent directory](http://mirror.rit.edu/cptc/2018/)) and we only use suricata alerts (`suricata_alert.json`). So, essentially, you will get six files: `suricata_alert_t1.json`, `suricata_alert_t2.json`, `suricata_alert_t5.json`, `suricata_alert_t7.json`, `suricata_alert_t8.json`, `suricata_alert_t9.json`.

**Comment by jzelenjak** [comment]
Regarding your second question, which paper do you mean exactly? If you refer to the main paper "Alert-Driven Attack Graph Generation Using S-PDFA", then Figure 6 also has the `70#1` format (see below, showing only a fragment, so that the state names and transitions are also visible):
![image](https://github.com/tudelft-cda-lab/SAGE/assets/45541174/4514db90-8a0c-4ca3-8965-bc9532df9622)

Note that the figure above shows the entire S-PDFA (i.e. red + blue + white states), while the image that you get does not include white sinks (since they are printed in a separate file, i.e. you have files `expName.txt.ff.final.json` and `expName.txt.ff.finalsinks.json`).

The reason that the states have `70#1` format is that this is the format used by [FlexFringe](https://github.com/tudelft-cda-lab/FlexFringe).

So, I don't see any problem with your experiments. Does that answer your question? If not, feel free to send another comment.

**Comment by hexing2333** [comment]
> Regarding your second question, which paper do you mean exactly? If you refer to the main paper "Alert-Driven Attack Graph Generation Using S-PDFA", then Figure 6 also has the `70#1` format (see below, showing only a fragment, so that the state names and transitions are also visible): ![image](https://user-images.githubusercontent.com/45541174/268171679-4514db90-8a0c-4ca3-8965-bc9532df9622.png)
> 
> Note that the figure above shows the entire S-PDFA (i.e. red + blue + white states), while the image that you get does not include white sinks (since they are printed in a separate file, i.e. you have files `expName.txt.ff.final.json` and `expName.txt.ff.finalsinks.json`).
> 
> The reason that the states have `70#1` format is that this is the format used by [FlexFringe](https://github.com/tudelft-cda-lab/FlexFringe).
> 
> So, I don't see any problem with your experiments. Does that answer your question? If not, feel free to send another comment.

Thank you very much for your answer. I have no further questions,currently. Thank you very much. It has been very useful to me

**Comment by azqanadeem** [comment]
Hi @hexing2333, I will just add that the reason your model looks different is because FlexFringe is constantly getting updated, e.g., when we developed SAGE in 2021, the S-PDFA model never had any colored states (we add colors in SAGE to denote severity). Since the FlexFringe tool uses the red-blue state merging (you can read more about it in the flexfringe paper), now the core states in the model are colored red. I understand it makes it difficult to reproduce the paper's results. If that is indeed what you are after, I can share an older .exe file for FlexFringe that you can use to get the same model, though there are no guarantees that it would still work.

**Comment by hexing2333** [comment]
I see. Thank you very much for your reply. I will carefully read the relevant libraries and papers of FlexFringe again. And if quite convenient, I hope to get an old version .exe of&nbsp;FlexFringe. Here is my email address, ***@***.*** Thank you very much for your reply!&nbsp;



---Original---
From: "Azqa ***@***.***&gt;
Date: Fri, Sep 15, 2023 21:54 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [tudelft-cda-lab/SAGE] A problem about the dataset (Issue #45)




 
Hi @hexing2333, I will just add that the reason your model looks different is because FlexFringe is constantly getting updated, e.g., when we developed SAGE in 2021, the S-PDFA model never had any colored states (we add colors in SAGE to denote severity). Since the FlexFringe tool uses the red-blue state merging (you can read more about it in the flexfringe paper), now the core states in the model are colored red. I understand it makes it difficult to reproduce the paper's results. If that is indeed what you are after, I can share an older .exe file for FlexFringe that you can use to get the same model, though there are no guarantees that it would still work.
