### ISSUE TITLE
Possible to put a sample file

### ISSUE THREAD

**Issue by onurd86** [tudelft-cda-lab/SAGE#8]
Hi,

Thanks for the source code. Is it possible to put a sample input file I tried some .json files in http://cptc.rit.edu/2018/t2/events/ but I guess it does not work for all the .json files there.

**Comment by azqanadeem** [comment]
The error you get is because the .json files by default contain one json object in each line, while the parser assumes that the .json file will be a list of json objects. It's a simple fix: either make the .json file a list of json objects or change lines 1346-1348 to:
```
unparsed_file = []
with open(fname, 'r') as f:
        for line in f:
            unparsed_file.append(json.loads(line))
```

**Comment by onurd86** [comment]
Thanks for your response. I saw many json files under: http://cptc.rit.edu/2018/t2/events/, the one which worked for me is: http://cptc.rit.edu/2018/t1/events/suricata_alert.json.gz. It did not work for other json files in the same directory. My suggestion is: this file can be put in this repository as sample input.

**Comment by azqanadeem** [comment]
Ah, I understand. Yes, that is intended because suricata_alert.json.gz is the only compressed folder that contains Suricata alerts. The other folders contain other types of logs which we do not currently support. I will upload a smaller version of one of the alert files in the repo. Thank you for the suggestion!
